deepfake_detection/urls.py
from django.contrib import admin
from django.urls import path
from detection_app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home,name='home'),
    path("result/",views.result,name='result'),
    path("advocates/",views.advocates,name='advocates'),
]

detection_app/models.py
from django.db import models

# Create your models here.

detection_app/forms.py
from django import forms

class UploadFileForm(forms.Form):
    video = forms.FileField()

detection_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,JsonResponse
from .forms import UploadFileForm
from .data import advocates as adv,districts
from detection_app.utils import handle_uploaded_file, mail
# Create your views here.

def home(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            print("success")
            result = handle_uploaded_file(request.FILES["video"])
            # result = 'success'
            return render(request,'result.html', {'result':result})

    else:
        form = UploadFileForm()
    return render(request,'home.html', {'form':form})

def result(request):
    action = request.GET.get('action')
    if action=="report":
        data = {}

        data={
            'name':request.GET.get('name'),
            'path' :  request.GET.get('path'),
            'pnum' :  request.GET.get('pnum'),
            'email' :  request.GET.get('email'),
            'complaint' :  request.GET.get('complaint'),
        }

         
        mail(data)
        return JsonResponse({'success':True})
    return render(request,'result.html')

def advocates(request):
    return render(request,'advocates.html',{'advocates':adv,'districts':districts})

detection_app/templates/advocates.html
{% extends "default.html" %} {% load static %} 
{% block page %}
<div class="container">

    <div id="contacts">
        <h2><span>Thiruvanathapuram</span></h2>
    <div class="d-flex gap-3" id="thiruvanathapuram">
        {% for adv in advocates.thiruvanathapuram %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Kollam</span></h2>
    <div class="d-flex gap-3" id="kollam">
        {% for adv in advocates.kollam %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
               
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Pathanamthitta</span></h2>
    <div class="d-flex gap-3" id="pathanamthitta">
        {% for adv in advocates.pathanamthitta %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Alapuzha</span></h2>
    <div class="d-flex gap-3" id="alapuzha">
        {% for adv in advocates.alapuzha %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
             
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Kottyam</span></h2>
    <div class="d-flex gap-3" id="kottyam">
        {% for adv in advocates.kottyam %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
               
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Ernakulam</span></h2>
    <div class="d-flex gap-3" id="ernakulam">
        {% for adv in advocates.ernakulam %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
              
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
               
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Idukki</span></h2>
    <div class="d-flex gap-3" id="idukki">
        {% for adv in advocates.idukki %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
               
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
                
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Kasaragod</span></h2>
    <div class="d-flex gap-3" id="kasaragod">
        {% for adv in advocates.kasaragod %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
                
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Kannur</span></h2>
    <div class="d-flex gap-3" id="kannur">
        {% for adv in advocates.kannur %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
              
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Wayanad</span></h2>
    <div class="d-flex gap-3" id="wayanad">
        {% for adv in advocates.wayanad %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
             
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
               
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Kozhikode</span></h2>
    <div class="d-flex gap-3" id="kozhikode">
        {% for adv in advocates.kozhikode %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
             
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
              
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Malappuram</span></h2>
    <div class="d-flex gap-3" id="malappuram">
        {% for adv in advocates.malappuram %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
             
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
              
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Palakkad</span></h2>
    <div class="d-flex gap-3" id="">
        {% for adv in advocates.palakkad %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
             
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2><span>Thrissur</span></h2>
    <div class="d-flex gap-3" id="thrissur">
        {% for adv in advocates.thrissur %}
        <div class="card col-2 contact-card">
            <div class="card-body" >
                <h5><span>{{adv.name}}</span></h5>
                
                    <a href="tel:{{adv.contact}}"><i class="fa-solid fa-phone"></i> {{adv.contact}}</a>
                    <a href="{{adv.location}}" target="_blank">
                        <h6><i class="fa-solid fa-location-dot"></i> Location</h6>
                    </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>



<script src="{% static 'jquery-3.7.1.js' %}"></script>
<script src="{% static 'Javascript/home.js' %}"></script>
{% endblock %}

detection_app/templates/default.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dar">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><span class="navbar-brand mb-0 h1">DeepFake <span>Detector</span></span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block page %}
    {% endblock %}
    <!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

detection_app/templates/home.html
{% extends "default.html" %} {% load static %} 
{% block page %}
<div class="container-fluid ">
    <div class="d-flex justify-content-around align-items-center " style="height: 90vh;">
        <div class="text-sart col-5 d-flex flex-column gap-2">
            <h1 id="heading">DeepFake <span>Detector</span></h1>
            <div>
                <p >
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis praesentium obcaecati deserunt eius,
                     impedit tempore harum quidem esse soluta enim inventore voluptatibus ratione? Officia quidem voluptatibus,
                      commodi adipisci eum facere.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis consectetur quas quis illo sit odit, mollitia a repellat pariatur est?
                </p>
            </div>
        </div>
        
        <div class="d-flex flex-column justify-content-around align-items-center h-100 col-5" >
            <div >
                <img src="{% static 'images/img1.jpg' %}" alt="" class="home_img1" width="350">
            </div>
            <div id="input">
                <form method="post" enctype="multipart/form-data" class="d-flex flex-column justify-content-center align-items-center">
                    {% csrf_token %}
                    <!-- {{ form.as_p }}   -->
                    <div class="form-group mb-3">
                        <input class="form-control" type="file" name="video" required id="id_video">
                    </div>
                    <button class="btn btn-secondary" type="submit" id="upload_btn">Upload</button>
                </form>
            </div>
            <div id="loading">
                <div class="loader m-auto"></div>
                <div class="loader_uploading m-auto"></div>
                <div class="loader_processing"></div>   
            </div>
          
        </div>
        
    </div>
</div>

<script src="{% static 'jquery-3.7.1.js' %}"></script>
<script src="{% static 'Javascript/home.js' %}"></script>
{% endblock %}

detection_app/templates/result.html
{% extends "default.html" %} {% load static %} 
{% block page %}



<div class="container-fluid">
    <div class="d-flex justify-content-around align-items-center gap-5" style="height: 90vh;">
        <div class="d-flex justify-content-center align-items-center col-4 h-100">

            <video width="530" height="440" controls autoplay>
                <source src="{% static result.path %}" > </source>
            </video>
        </div>
        <div class=" d-flex flex-column justify-content-center align-items-start col-4 h-100">
                {% if result.output%}
                <h1>This Video is Real</h1>
                <p>There is a <span>{{result.confidence}}%</span> chance that this Video is <span>Real</span></p>
                {% else %}
                <h1>This Video is AI Generated </h1>
                <p>There is a <span>{{result.confidence}}%</span> chance that this Video was <span>Edited or Generated by an AI</span></p>
                {% endif %}
                <div class="d-flex gap-3">
                    <a href="{% url 'home' %}"><button class="btn btn-secondary">Upload Another</button></a>
                    <input type="text" class="d-none" value={{result.path}} id="video_path"/>
                    {% if not result.output%}
                    <button id="report_btn" class=" btn report-btn" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" >Report</button>
                    <a href="{% url 'advocates' %}"><button class="btn btn-secondary">Advocate Details</button></a>
                    {% endif %}
                </div>
        </div>
    </div>
</div>


  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" >
      <div class="modal-content" id="modal-body">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Report Video</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    class="form-control"
                    id="name"
                    name="name"
                    placeholder="Enter the Name"
                />
            </div>
            <div class="form-group">
                <label for="pnum">Phone Number</label>
                <input
                    type="text"
                    class="form-control"
                    id="pnum"
                    name="pnum"
                    placeholder="Enter the Phone NUmber"
                />
            </div>
            <div class="form-group">
                <label for="email">Email ID</label>
                <input
                    type="email"
                    class="form-control"
                    id="email"
                    name="email"
                    placeholder="Enter the Email ID"
                />
            </div>
            <div class="form-group">
                <label for="complaint">Complaint</label>
                <textarea
                    type="text"
                    class="form-control"
                    id="complaint"
                    name="complaint"
                    placeholder="Enter the complaint"
                    rows="5"
                ></textarea>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn report-btn" id="report" data-bs-dismiss="modal">Report</button>
        </div>
      </div>
    </div>
  </div>






<script src="{% static 'jquery-3.7.1.js' %}"></script>
<script src="{% static 'Javascript/home.js' %}"></script>
{% endblock %}